const mongoose = require("mongoose");

const documenstSchema = mongoose.Schema({
  name: { type: String },
  image: { type: String },
});

const newPanSchema = mongoose.Schema({
  category: { type: String},
  date: { type: String},
  city: { type: String},
  areaCode: { type: String },
  aotype: { type: String },
  rangeCode: { type: String },
  aoNo: { type: String },
  firstName: { type: String},
  middleName: { type: String },
  lastName: { type: String},
  title: { type: String},
  gender: { type: String},
  dateOfBirth: { type: String},
  monthOfBirth: { type: String},
  yearOfBirth: { type: String},
  residenceAddress: { type: String },
  flatNumber: { type: String},
  premisesName: { type: String },
  roadName: { type: String},
  area: { type: String},
  cityDistrict: { type: String},
  state: { type: String},
  zipCode: { type: String},
  country: { type: String},
  telephoneISDCode: { type: String},
  telephoneNumber: { type: String},
  email: { type: String},
  aadhaarNumber: { type: String},
  aadhaarName: { type: String },
  sourceOfIncome: { type: String},
  identityProof: { type: String },
  addressProof: { type: String },
  dobProof: { type: String },
  declarationCapacity: { type: String},
  verifierName: { type: String},
  verifierPlace: { type: String},
  verificationDate: { type: String},
  requiredOption: { type: String },
  userID: { type: String},
  vendorID: { type: String},
  tokenNumber: { type: String},
  NameOnCard: { type: String},
  father_LName: { type: String},
  father_MName: { type: String },
  father_FName: { type: String},
  isDoneFromUser: { type: Boolean },
  PanFee: { type: Number},
  //new add for others type
  organization: { type: String},
    officeName:{ type: String},
    registrationNumber:{ type: String},
    officetitle:{ type: String},
    officeflatNumber:{ type: String},
    officepremisesName:{ type: String},
    officeroadName:{ type: String},
    officearea:{ type: String},
    officecityDistrict:{ type: String},
    officestate:{ type: String},
    officezipCode:{ type: String},
    officecountry:{ type: String},
});

const NewPanModel = mongoose.model("newPancard", newPanSchema);

module.exports = {
  NewPanModel,
};
